plugin: amazon.aws.aws_ec2

regions:
  - us-east-1

keyed_groups:
  - key: tags
    prefix: tag

filters:
  tag:env: dev

hostnames:
  - ip-address
  - dns-name
  - tag:Name
  - tag:env
  - private-ip-address
compose:



