---
- name: Nginx Install and Configure
  hosts: webservers
  become: true
  vars:
    app_name: "react-frontend"
    app_path: 
    nginx_port: 80


  tasks:
  - name: Update apt
    ansible.builtin.apt:
      update_cache: yes
    when: ansible_os_family == "Debian"
  
  - name: Install Nginx
    ansible.builtin.apt:
      name: nginx
      state: present
    when: ansible_os_family == "Debian"
  
  - name: Configure Nginx for React App
    template:
      src: nginx.conf.j2
      dest: /etc/nginx/nginx.conf
    when: ansible_os_family == "Debian"
  
  - name: Enable Nginx site
    file:
      src: /etc/nginx/sites-available/${{ app_name }}
      dest: /etc/nginx/sites-enabled/${{ app_name }}
      state: link
    when: ansible_os_family == "Debian"
  
  - name: Start Nginx
    service:
      name: nginx
      state: started
    when: ansible_os_family == "Debian"
