name: Infrastructure

on:
    pull_request:
    push:
        branches:
            - main

jobs:
    Infrastructure-Cost:
        permissions:
            id-token: write
            contents: read
            pull-requests: write
        if: github.event_name == 'pull_request'
        uses: The-Wild-West/Shareable-Workflows/.github/workflows/terraform-cost.yaml@main
        secrets:
            admin_account_id: ${{ secrets.ADMIN_ACCOUNT_ID }}
            role_name: ${{ secrets.OIDC_ROLE_PREFIX }}
    Infrastructure-Deployment:
        permissions:
            id-token: write
            contents: read
        if: github.event_name == 'push' || github.event.pull_request.merged == true
        uses: The-Wild-West/Shareable-Workflows/.github/workflows/terraform-apply.yaml@main
        with:
            environment: 'root'
        secrets:
            admin_account_id: ${{ secrets.ADMIN_ACCOUNT_ID }}
            role_name: ${{ secrets.OIDC_ROLE_PREFIX }}
    Ansible-Configuration:
        permissions:
            id-token: write
            contents: read
        runs-on: ubuntu-latest
        if: github.event_name == 'push' || github.event.pull_request.merged == true
        steps:
            - name: AWS Login - Management Environment
              uses: aws-actions/configure-aws-credentials@v4
              with:
                role-to-assume: arn:aws:iam::${{ secrets.admin_account_id }}:role/${{ secrets.role_name }}
                aws-region: us-east-1
            - name: Copy Inventory Files
              shell: bash
              run: |
                aws ssm send-command \
                --instance-ids "i-0911f2c2c3c485be7" \
                --document-name "AWS-SendCommand" \
                --parameters '{"commands":["mkdir -p /home/ubuntu/ansible","cd /home/ubuntu/ansible","git clone https://github.com/The-Wild-West/Account-Infrastructure-Orchestration.git .","cp -r inventory /etc/ansible/"]}' \
                --region us-east-1  
              
    