name: Infrastructure

on:
    pull_request:

jobs:
    Infrastructure-Deployment:
        permissions:
            id-token: write
            contents: read
            pull-requests: write
        uses: The-Wild-West/Shareable-Workflows/.github/workflows/terraform-cost.yaml@main
        secrets:
            admin_account_id: ${{ secrets.ADMIN_ACCOUNT_ID }}
            role_name: ${{ secrets.OIDC_ROLE_PREFIX }}
