name: Infrastructure

on:
    pull_request:
    push:
        branches:
            - main
            - feature-workflow

jobs:
    Infrastructure-Cost:
        permissions:
            id-token: write
            contents: read
            pull-requests: write
        if: github.event_name == 'pull_request'
        uses: The-Wild-West/Shareable-Workflows/.github/workflows/terraform-cost.yaml@main
        secrets:
            admin_account_id: ${{ secrets.ADMIN_ACCOUNT_ID }}
            role_name: ${{ secrets.OIDC_ROLE_PREFIX }}
    Infrastructure-Deployment:
        permissions:
            id-token: write
            contents: read
        if: github.event_name == 'push' || github.event.pull_request.merged == true
        uses: The-Wild-West/Shareable-Workflows/.github/workflows/terraform-apply.yaml@uat
        with:
            environment: 'root'
        secrets:
            admin_account_id: ${{ secrets.ADMIN_ACCOUNT_ID }}
            role_name: ${{ secrets.OIDC_ROLE_PREFIX }}
    Write-Outputs:
        runs-on: ubuntu-latest
        needs: Infrastructure-Deployment
        if: github.event_name == 'push' || github.event.pull_request.merged == true
        outputs:
            ansible_control_node_id: ${{ steps.convert_outputs.outputs.ansible_control_node_id }}
        steps:
            - name: Display Outputs
              id: display_outputs
              run: |
                cat << 'EOF' >> GITHUB_OUTPUT
                all_outputs_json=${{ needs.Infrastructure-Deployment.outputs.all_outputs_json }}
                EOF
            - name: Convert Outputs
              id: convert_outputs
              run: |
                CONTROL_NODE_ID=$(echo '${{ needs.Infrastructure-Deployment.outputs.all_outputs_json }}' | jq -r '.control_node_id.value')
                echo "$CONTROL_NODE_ID"
                echo "ansible_control_node_id=$CONTROL_NODE_ID" >> GITHUB_OUTPUT
    Ansible-Configuration:
        needs: Write-Outputs
        permissions:
            id-token: write
            contents: read
        runs-on: ubuntu-latest
        if: github.event_name == 'push' || github.event.pull_request.merged == true
        steps:
            - name: AWS Login - Management Environment
              uses: aws-actions/configure-aws-credentials@v4
              with:
                role-to-assume: arn:aws:iam::${{ secrets.ADMIN_ACCOUNT_ID }}:role/${{ secrets.OIDC_ROLE_PREFIX }}
                aws-region: us-east-1
            - name: Copy Inventory Files
              shell: bash
              run: |
                echo '${{ needs.Write-Outputs.outputs.ansible_control_node_id }}'
                aws ssm send-command \
                --instance-ids ${{ needs.Write-Outputs.outputs.ansible_control_node_id }} \
                --document-name "AWS-RunShellScript" \
                --parameters '{"commands":["rm -rf /home/ubuntu/ansible","mkdir -p /home/ubuntu/ansible","cd /home/ubuntu/ansible","git clone https://github.com/The-Wild-West/Account-Infrastructure-Orchestration.git .","sudo rm -rf /etc/ansible/inventory","sudo cp -r inventory /etc/ansible/"]}' \
                --region us-east-1  
              
    