name: Test

on:
    push:
        branches:
        - dev
jobs:
    Test:
        runs-on: ubuntu-latest
        steps:
            - name: status
              shell: bash
              run: echo pass