name: Infrastructure

on:
    pull_request:
    push:
        branches:
            - main

jobs:
    Infrastructure-Cost:
        permissions:
            id-token: write
            contents: read
            pull-requests: write
        if: github.event_name == 'pull_request'
        uses: The-Wild-West/Shareable-Workflows/.github/workflows/terraform-cost.yaml@main
        secrets:
            admin_account_id: ${{ secrets.ADMIN_ACCOUNT_ID }}
            role_name: ${{ secrets.OIDC_ROLE_PREFIX }}
    Infrastructure-Deployment:
        permissions:
            id-token: write
            contents: read
        if: github.event_name == 'push' || github.event.pull_request.merged == true
        uses: The-Wild-West/Shareable-Workflows/.github/workflows/terraform-apply.yaml@main
        with:
            environment: 'root'
        secrets:
            admin_account_id: ${{ secrets.ADMIN_ACCOUNT_ID }}
            role_name: ${{ secrets.OIDC_ROLE_PREFIX }}